object dmMonitoringServer: TdmMonitoringServer
  OldCreateOrder = False
  OnCreate = DataModuleCreate
  OnDestroy = DataModuleDestroy
  Left = 709
  Top = 302
  Height = 324
  Width = 504
  object RSERVER1: TDXServerCore
    ReleaseDate = '2003-04-15'
    ListenerThreadPriority = tpNormal
    SpawnedThreadPriority = tpNormal
    ProtocolToBind = wpTCPOnly
    ServerPort = 3431
    Suspend = False
    UseSSL = False
    UseNagle = False
    UseThreadPool = True
    SocketOutputBufferSize = bsfNormal
    SocketQueueSize = 100
    ServerType = stThreadBlocking
    ThreadCacheSize = 20
    Timeout = 10000
    OnNewConnect = RSERVER1NewConnect
    Left = 24
    Top = 8
  end
  object DXUnicastDataQueue1: TDXUnicastDataQueue
    ReleaseDate = '2003-04-15'
    ThreadPriority = tpHigher
    IgnoreOverruns = True
    ThreadStart = False
    Left = 24
    Top = 55
  end
  object ControlServer: TDXServerCore
    ReleaseDate = '2003-04-15'
    ListenerThreadPriority = tpNormal
    SpawnedThreadPriority = tpNormal
    ProtocolToBind = wpTCPOnly
    ServerPort = 3431
    Suspend = False
    UseSSL = False
    UseNagle = False
    UseThreadPool = True
    SocketOutputBufferSize = bsfNormal
    SocketQueueSize = 100
    ServerType = stThreadBlocking
    ThreadCacheSize = 20
    Timeout = 10000
    OnNewConnect = ControlServerNewConnect
    Left = 104
    Top = 8
  end
  object ControlDataQueue: TDXUnicastDataQueue
    ReleaseDate = '2003-04-15'
    IgnoreOverruns = True
    ThreadStart = False
    Left = 104
    Top = 55
  end
  object ServerStartTimer: TTimer
    Enabled = False
    Interval = 10000
    OnTimer = ServerStartTimerTimer
    Left = 16
    Top = 120
  end
end
