CREATE TABLE [TB_ACCESSDEVICE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AC_MCUIP]varchar(24) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_MCUPORT]varchar(5) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_MCUID]varchar(7) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_ECUID]varchar(2) COLLATE Korean_Wansung_CI_AS DEFAULT '00' NOT NULL,
  [AC_LASTCONNECTED]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_DEVICENAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_DONGCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_FLOORCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_AREACODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_VIEWSEQ]int NULL,
  [AC_NODENO]int NOT NULL,
  [AC_ACTYPE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_ATTYPE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_FDTYPE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_PTTYPE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_TOTWIDTH]int NULL,
  [AC_TOTHEIGHT]int NULL,
  [AC_CURX]int NULL,
  [AC_CURY]int NULL,
  [AC_LOCATEUSE]char(1) COLLATE Korean_Wansung_CI_AS  DEFAULT 'N' NULL,
  [AC_LOCALRELAY]varchar(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'N' NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AC_NODENO], [AC_MCUID], [AC_ECUID])
);

CREATE TABLE [TB_ACCESSEVENT] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AC_DATE]varchar(8) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_TIME]varchar(6) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_NODENO]int DEFAULT 0 NOT NULL,
  [DO_DOORNO]char(1) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_READERNO]char(1) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [CA_CARDNO]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_DOORPOSI]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_INPUTTYPE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_DOORMODE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_PERMITMODE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [PE_PERMITCODE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_INSERTDATE]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_INSERTOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_MCUID]varchar(7) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_ECUID]varchar(2) COLLATE Korean_Wansung_CI_AS NOT NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AC_DATE], [AC_TIME], [AC_NODENO], [AC_MCUID], [AC_ECUID], [DO_DOORNO], [CA_CARDNO])
);

CREATE TABLE [TB_ADMIN] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AD_USERID]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AD_USERPW]varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
  [AD_USERNAME]varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
  [GR_GRADECODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [AD_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [AD_UPDATEOPERATER]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [AD_MASTER]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AD_USERID])
);

CREATE TABLE [TB_ADMINALARMDEVICE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AD_USERID]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AL_DEVICENO]int DEFAULT 0 NOT NULL,
  [AD_GUBUN]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AD_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [AD_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AD_USERID], [AL_DEVICENO])
);

CREATE TABLE [TB_ADMINCOMPANY] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AD_USERID]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [CO_COMPANYCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [CO_DEPARTCODE]varchar(3) COLLATE Korean_Wansung_CI_AS DEFAULT '000' NOT NULL,
  [CO_GUBUN]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AD_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [AD_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AD_USERID], [CO_COMPANYCODE], [CO_DEPARTCODE])
);

CREATE TABLE [TB_ADMINDOOR] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AD_USERID]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_NODENO]int DEFAULT 0 NOT NULL,
  [DO_DOORNO]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '1' NOT NULL,
  [AD_GUBUN]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AD_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [AD_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_MCUID]varchar(7) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_ECUID]varchar(2) COLLATE Korean_Wansung_CI_AS NOT NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AD_USERID], [AC_NODENO], [DO_DOORNO], [AC_MCUID], [AC_ECUID])
);

CREATE TABLE [TB_ADMINFOOD] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AD_USERID]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_NODENO]int NOT NULL,
  [AC_MCUID]varchar(7) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_ECUID]varchar(2) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AD_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [AD_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [FO_DOORNO]char(1) COLLATE Korean_Wansung_CI_AS NOT NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AD_USERID], [AC_NODENO], [AC_MCUID], [AC_ECUID], [FO_DOORNO])
);

CREATE TABLE [TB_ALARMCHECKCODE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AL_ALARMCHECKCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AL_ALARMCHECKCODENAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AL_ALARMCHECKCODE])
);

CREATE TABLE [TB_ALARMDEVICE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AL_DEVICENO]int NOT NULL,
  [AC_NODENO]int NOT NULL,
  [AL_ZONENUM]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '1' NOT NULL,
  [AL_ZONENAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_LASTMODE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_VIEWSEQ]int NULL,
  [AC_MCUID]varchar(7) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_ECUID]varchar(2) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AL_LOCATEUSE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_TOTWIDTH]int NULL,
  [AL_TOTHEIGHT]int NULL,
  [AL_CURX]int NULL,
  [AL_CURY]int NULL,
  [LO_DONGCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_FLOORCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_AREACODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [TM_MEETCODE]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [TM_MEETFLOOR]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [TM_MEETNAME]varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_VIEWMODE]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'Y' NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AL_DEVICENO])
);

CREATE TABLE [TB_ALARMDEVICETYPECODE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AL_ALARMDEVICETYPECODE]varchar(2) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AL_ALARMDEVICETYPENAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AL_ALARMDEVICETYPECODE])
);

CREATE TABLE [TB_ALARMEVENT] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AL_DATE]varchar(8) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AL_TIME]varchar(6) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AL_DEVICENO]int NOT NULL,
  [AL_MSGNO]char(1) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AL_ALARMDEVICETYPECODE]varchar(2) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_SUBADDR]varchar(2) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_ZONECODE]varchar(2) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_ALARMMODECODE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_ZONENO]varchar(2) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_ZONESTATE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_ALARMSTATUSCODE]varchar(2) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_ISALARM]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_OPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_INPUTTIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_INPUTOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_CHECKOK]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_CHECKCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_CHECKMSG]varchar(100) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AL_DATE], [AL_TIME], [AL_DEVICENO], [AL_MSGNO])
);

CREATE TABLE [TB_ALARMMODECODE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AL_ALARMMODECODE]char(1) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AL_ALARMMODENAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AL_ALARMMODECODE])
);

CREATE TABLE [TB_ALARMSTATUSCODE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AL_ALARMSTATUSCODE]varchar(2) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AL_ALARMNAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [AL_ALARMVIEW]int NULL,
  [AL_ALARMGRADE]int NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AL_ALARMSTATUSCODE])
);

CREATE TABLE [TB_ATCODE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AT_ATCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AT_CODENAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_WORKSTARTTIME]varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_WORKENDTIME]varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_INFROMTIME]varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_INTOTIME]varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_NIGHTTIME]varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AT_ATCODE])
);

CREATE TABLE [TB_ATEVENT] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AT_DATE]varchar(8) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [CA_CARDNO]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AT_ATCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_DEFAULTINTIME]varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_DEFAULTOUTTIME]varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_INTIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_OUTTIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_INRESULT]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_OUTRESULT]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_INSERTTIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_INSERTOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_DEFAULTLATETIME]varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_HoliyDay]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_Night]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AT_CONTENT]varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AT_DATE], [CA_CARDNO])
);

CREATE TABLE [TB_CARD] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [CA_CARDNO]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [CA_GUBUN]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '1' NULL,
  [CA_CARDTYPE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [EM_CODE]varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
  [CO_COMPANYCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [CA_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [CA_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [FPMS_ID]int NULL,
  [FoodUse]varchar(1) COLLATE Korean_Wansung_CI_AS NULL,
  [Relay_Send]varchar(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'N' NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [CA_CARDNO])
);

CREATE TABLE [TB_COMPANY] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [CO_COMPANYCODE]varchar(3) COLLATE Korean_Wansung_CI_AS DEFAULT '000' NOT NULL,
  [CO_DEPARTCODE]varchar(3) COLLATE Korean_Wansung_CI_AS DEFAULT '000' NOT NULL,
  [CO_NAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [CO_GUBUN]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [CO_CHARGE]varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
  [CO_TELNUM]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [CO_COMPANYCODE], [CO_DEPARTCODE])
);

CREATE TABLE [TB_CONFIG] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [CO_CONFIGGROUP]varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [CO_CONFIGCODE]varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [CO_CONFIGVALUE]varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
  [CO_CONFIGDETAIL]varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [CO_CONFIGGROUP], [CO_CONFIGCODE])
);

CREATE TABLE [TB_CURRENTDAEMON] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [CU_STATECODE]varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [CU_STATEVALUE]varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [CU_STATECODE])
);

CREATE TABLE [TB_DATASHARE] (
  [PR_GROUPCODE]varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [PR_PROGRAMID]varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [DA_DETAIL]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([PR_GROUPCODE], [PR_PROGRAMID], [GROUP_CODE])
);

CREATE TABLE [TB_DEVICECARDNO] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [CA_CARDNO]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [DE_DOOR1]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_DOOR2]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_USEACCESS]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_USEALARM]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_TIMECODE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_PERMIT]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_RCVACK]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_MCUID]varchar(7) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_ECUID]varchar(2) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_NODENO]int NOT NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [CA_CARDNO], [AC_MCUID], [AC_ECUID], [AC_NODENO])
);

CREATE TABLE [TB_DEVICECARDNO_HIS] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [CA_CARDNO]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [DE_DOOR1]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_DOOR2]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_USEACCESS]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_USEALARM]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_TIMECODE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_PERMIT]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_RCVACK]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_MCUID]varchar(7) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_ECUID]varchar(2) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_NODENO]int NOT NULL,
  [SEQ]int IDENTITY(1, 1) NOT NULL,
  [HIS_OPER]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([SEQ])
);

ALTER TRIGGER [TB_DEVICECARDNO_INSERT] ON [TB_DEVICECARDNO]
WITH EXECUTE AS CALLER
FOR INSERT
AS
BEGIN
  /* Trigger body */
  Insert INTO TB_DEVICECARDNO_HIS (HIS_OPER,GROUP_CODE,
  CA_CARDNO,DE_DOOR1,DE_DOOR2,DE_USEACCESS,DE_USEALARM,DE_TIMECODE,
  DE_PERMIT,DE_RCVACK,DE_UPDATETIME,DE_UPDATEOPERATOR,AC_MCUID,
  AC_ECUID,AC_NODENO) select 'INSERT',GROUP_CODE,
  CA_CARDNO,DE_DOOR1,DE_DOOR2,DE_USEACCESS,DE_USEALARM,DE_TIMECODE,
  DE_PERMIT,DE_RCVACK,DE_UPDATETIME,DE_UPDATEOPERATOR,AC_MCUID,
  AC_ECUID,AC_NODENO
  FROM INSERTED
END;

ALTER TRIGGER [TB_DEVICECARDNO_UPDATE] ON [TB_DEVICECARDNO]
WITH EXECUTE AS CALLER
FOR UPDATE
AS
BEGIN
  /* Trigger body */
  Insert INTO TB_DEVICECARDNO_HIS (HIS_OPER,GROUP_CODE,
  CA_CARDNO,DE_DOOR1,DE_DOOR2,DE_USEACCESS,DE_USEALARM,DE_TIMECODE,
  DE_PERMIT,DE_RCVACK,DE_UPDATETIME,DE_UPDATEOPERATOR,AC_MCUID,
  AC_ECUID,AC_NODENO) select 'UPDATE',GROUP_CODE,
  CA_CARDNO,DE_DOOR1,DE_DOOR2,DE_USEACCESS,DE_USEALARM,DE_TIMECODE,
  DE_PERMIT,DE_RCVACK,DE_UPDATETIME,DE_UPDATEOPERATOR,AC_MCUID,
  AC_ECUID,AC_NODENO
  FROM INSERTED
END;

ALTER TRIGGER [TB_DEVICECARDNO_DELETE] ON [TB_DEVICECARDNO]
WITH EXECUTE AS CALLER
FOR DELETE
AS
BEGIN
  /* Trigger body */
  Insert INTO TB_DEVICECARDNO_HIS (HIS_OPER,GROUP_CODE,
  CA_CARDNO,DE_DOOR1,DE_DOOR2,DE_USEACCESS,DE_USEALARM,DE_TIMECODE,
  DE_PERMIT,DE_RCVACK,DE_UPDATETIME,DE_UPDATEOPERATOR,AC_MCUID,
  AC_ECUID,AC_NODENO) select 'DELETE',GROUP_CODE,
  CA_CARDNO,DE_DOOR1,DE_DOOR2,DE_USEACCESS,DE_USEALARM,DE_TIMECODE,
  DE_PERMIT,DE_RCVACK,DE_UPDATETIME,DE_UPDATEOPERATOR,AC_MCUID,
  AC_ECUID,AC_NODENO
  FROM DELETED
END;

CREATE TABLE [TB_DEVICECARDNO_PROMISE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [DE_DOOR1]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_DOOR2]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_USEACCESS]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_USEALARM]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_TIMECODE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_PERMIT]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_RCVACK]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_MCUID]varchar(7) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_ECUID]varchar(2) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_NODENO]int NOT NULL,
  [PR_NAME]varchar(50) COLLATE Korean_Wansung_CI_AS NOT NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AC_MCUID], [AC_ECUID], [AC_NODENO], [PR_NAME])
);

CREATE TABLE [TB_DEVICESCHEDULE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [DO_DOORNO]char(1) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [DE_DAYCODE]char(1) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [DE_CELL1TIME]varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_CELL1MODE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_CELL2TIME]varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_CELL2MODE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_CELL3TIME]varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_CELL3MODE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_CELL4TIME]varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_CELL4MODE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_CELL5TIME]varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_CELL5MODE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_RCVACK]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_MCUID]varchar(7) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_ECUID]varchar(2) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_NODENO]int NOT NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [DO_DOORNO], [DE_DAYCODE], [AC_MCUID], [AC_ECUID], [AC_NODENO])
);

CREATE TABLE [TB_DEVICETYPE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [DE_DEVICETYPE]varchar(2) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [DE_TYPENAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_ACCESSGROUP]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_ATGROUP]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_ALARMGROUP]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DE_FOODGROUP]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [DE_DEVICETYPE])
);

CREATE TABLE [TB_DOOR] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [DO_DOORNO]char(1) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [DO_DOORNONAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [DO_LASTMODE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_NODENO]int NOT NULL,
  [AC_MCUID]varchar(7) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_ECUID]varchar(2) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [DO_VIEWSEQ]int NULL,
  [DO_TOTWIDTH]int NULL,
  [DO_TOTHEIGHT]int NULL,
  [DO_CURX]int NULL,
  [DO_CURY]int NULL,
  [DO_LOCATEUSE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_DONGCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_FLOORCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_AREACODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [FPMS_ID]int NULL,
  [DO_LOCALRELAY]varchar(1) COLLATE Korean_Wansung_CI_AS NULL,
  [DO_STATEREVERSE]varchar(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'N' NULL,
  [Relay_Send]varchar(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'N' NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [DO_DOORNO], [AC_NODENO], [AC_MCUID], [AC_ECUID])
);

CREATE TABLE [TB_EMPLOYEE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [EM_CODE]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [CO_COMPANYCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [CO_DEPARTCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [PO_POSICODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [EM_NAME]varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
  [EM_COPHONE]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [EM_HOMEPHONE]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [EM_HANDPHONE]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [ZI_ZIPCODE]varchar(7) COLLATE Korean_Wansung_CI_AS NULL,
  [EM_ADDR1]varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
  [EM_ADDR2]varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
  [EM_JOINDATE]varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
  [EM_RETIREDATE]varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
  [EM_IMAGE]image NULL,
  [EM_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [EM_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [EM_CODE], [CO_COMPANYCODE])
);

CREATE TABLE [TB_FOOD] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AC_NODENO]int NOT NULL,
  [AC_MCUID]varchar(7) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_ECUID]varchar(2) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [FO_DOORNO]char(1) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [FO_NAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_DONGCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_FLOORCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_AREACODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [FO_TOTWIDTH]int NULL,
  [FO_TOTHEIGHT]int NULL,
  [FO_CURX]int NULL,
  [FO_CURY]int NULL,
  [FO_LOCATEUSE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [FO_AMTPER]int DEFAULT 100 NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AC_NODENO], [AC_MCUID], [AC_ECUID], [FO_DOORNO])
);

CREATE TABLE [TB_FOODADMIN] (
  [CO_COMPANYCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [EM_CODE]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [FO_BREAKFIRST]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'N' NULL,
  [FO_LUNCH]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'N' NULL,
  [FO_DINNER]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'N' NULL,
  [FO_MIDNIGHT]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'N' NULL,
  [FO_MONEY]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'N' NULL,
  [FO_WEEK]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'N' NULL,
  [FO_WEEKEND]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'N' NULL,
  [FO_HOLIDAY]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'N' NULL,
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
  PRIMARY KEY CLUSTERED ([CO_COMPANYCODE], [EM_CODE], [GROUP_CODE])
);

CREATE TABLE [TB_FOODCODE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [FO_FOODCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [FO_CODENAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [FO_STARTTIME]varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
  [FO_ENDTIME]varchar(4) COLLATE Korean_Wansung_CI_AS NULL,
  [FO_AMT]int DEFAULT 5000 NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [FO_FOODCODE])
);

CREATE TABLE [TB_FOODEVENT] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [FO_DATE]varchar(8) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [FO_TIME]varchar(6) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_NODENO]int NOT NULL,
  [FO_DOORNO]char(1) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [CA_CARDNO]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [FO_FOODCODE]varchar(3) COLLATE Korean_Wansung_CI_AS NULL,
  [FO_PERMIT]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [FO_INSERTTIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [FO_INSERTOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [FO_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [FO_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_MCUID]varchar(7) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_ECUID]varchar(2) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [FO_CONTENT]varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
  [FO_FOODAMT]int DEFAULT 0 NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [FO_DATE], [FO_TIME], [AC_NODENO], [FO_DOORNO], [CA_CARDNO], [AC_MCUID], [AC_ECUID])
);

CREATE TABLE [TB_GRADE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [GR_GRADECODE]varchar(3) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [GR_GARDENAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [GR_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [GR_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [GR_GRADECODE])
);

CREATE TABLE [TB_GRADEPROGRAM] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [GR_GRADECODE]varchar(3) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [PR_GROUPCODE]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [PR_PROGRAMID]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '0000000000' NOT NULL,
  [GR_GUBUN]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_UPDATEDATE]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [GR_UPDATE]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'Y' NULL,
  [GR_INSERT]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'Y' NULL,
  [GR_DELETE]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT 'Y' NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [GR_GRADECODE], [PR_PROGRAMID])
);

CREATE TABLE [TB_HOLIDAY] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [HO_DAY]varchar(8) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [HO_DESC]varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
  [HO_SEND]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [HO_DAY])
);

CREATE TABLE [TB_HOLIDAY_DEVICE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [HO_DAY]varchar(8) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [HO_DESC]varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
  [HO_SEND]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_NODENO]int NOT NULL,
  [AC_MCUID]varchar(7) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [AC_ECUID]varchar(2) COLLATE Korean_Wansung_CI_AS NOT NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [HO_DAY], [AC_NODENO], [AC_MCUID], [AC_ECUID])
);

CREATE TABLE [TB_LOCATION] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [LO_DONGCODE]varchar(3) COLLATE Korean_Wansung_CI_AS DEFAULT '000' NOT NULL,
  [LO_FLOORCODE]varchar(3) COLLATE Korean_Wansung_CI_AS DEFAULT '000' NOT NULL,
  [LO_AREACODE]varchar(3) COLLATE Korean_Wansung_CI_AS DEFAULT '000' NOT NULL,
  [LO_NAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_GUBUN]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_CADIMAGE]image NULL,
  [LO_IMAGEUSE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [LO_DONGCODE], [LO_FLOORCODE], [LO_AREACODE])
);

CREATE TABLE [TB_LOWDATA] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [SEQ]int IDENTITY(1, 1) NOT NULL,
  [LO_DATE]varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
  [AC_NODENO]int NULL,
  [LO_IP]varchar(24) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_PORT]varchar(5) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_MCUID]varchar(7) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_ECUID]varchar(2) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_TXRX]varchar(2) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_COMMAND]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_LOWDATA]varchar(200) COLLATE Korean_Wansung_CI_AS NULL,
  [LO_INSERTTIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [SEQ])
);

CREATE TABLE [TB_MONTHAT] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [MO_MONTH]varchar(6) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [CA_CARDNO]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [MO_01]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_02]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_03]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_04]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_05]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_06]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_07]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_08]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_09]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_10]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_11]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_12]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_13]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_14]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_15]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_16]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_17]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_18]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_19]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_20]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_21]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_22]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_23]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_24]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_25]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_26]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_27]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_28]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_29]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_30]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_31]char(1) COLLATE Korean_Wansung_CI_AS DEFAULT '0' NULL,
  [MO_ATCNT]int DEFAULT 0 NULL,
  [MO_JIKAKCNT]int DEFAULT 0 NULL,
  [MO_JOTAECNT]int DEFAULT 0 NULL,
  [MO_NIGHTCNT]int DEFAULT 0 NULL,
  [MO_HOLIDAYCNT]int DEFAULT 0 NULL,
  [MO_TOTATCNT]int DEFAULT 0 NULL,
  [MO_ABSENCECNT]int DEFAULT 0 NULL,
  [MO_NIGHTTIME]int DEFAULT 0 NULL,
  [MO_HOLIDAYTIME]int DEFAULT 0 NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [MO_MONTH], [CA_CARDNO])
);

CREATE TABLE [TB_PERMITCODE] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [PE_PERMITCODE]char(1) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [PE_PERMITNAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [PE_PERMITCODE])
);

CREATE TABLE [TB_POSI] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [PO_POSICODE]varchar(3) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [PO_NAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [PO_POSICODE])
);

CREATE TABLE [TB_PROGRAMGROUP] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [PR_GROUPCODE]varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [PR_GROUPCODENAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [PR_VISIBLE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [GUBUN]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [PR_GROUPCODE])
);

CREATE TABLE [TB_PROGRAMID] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [PR_GROUPCODE]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [PR_PROGRAMID]varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [PR_PROGRAMNAME]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [PR_VISIBLE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  [PR_VIEWSEQ]int NULL,
  [CO_CONFIGCODE]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [PR_UPDATETIME]varchar(14) COLLATE Korean_Wansung_CI_AS NULL,
  [PR_UPDATEOPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [PR_ENABLE]char(1) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [PR_PROGRAMID])
);

CREATE TABLE [TB_SYSTEMLOG] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [SY_DATE]varchar(8) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [SY_TIME]varchar(6) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [SY_CLIENTIP]varchar(24) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [SY_OPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [SY_LOGDATA]varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [SY_DATE], [SY_TIME], [SY_CLIENTIP], [SY_OPERATOR])
);

CREATE TABLE [TB_USERCONFIG] (
  [GROUP_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS DEFAULT '1234567890' NOT NULL,
  [AD_USERID]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [US_CONFIGID]varchar(20) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [US_VALUE]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [US_CONFGROUP]varchar(10) COLLATE Korean_Wansung_CI_AS NOT NULL,
  PRIMARY KEY CLUSTERED ([GROUP_CODE], [AD_USERID], [US_CONFIGID], [US_CONFGROUP])
);

CREATE TABLE [TB_WORKLOG] (
  [WO_CODE]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [WO_COMMAND]varchar(10) COLLATE Korean_Wansung_CI_AS NULL,
  [WO_DATA]varchar(50) COLLATE Korean_Wansung_CI_AS NULL,
  [WO_TIME]datetime NULL,
  [WO_OPERATOR]varchar(10) COLLATE Korean_Wansung_CI_AS NULL
);

CREATE TABLE [TB_ZIPCODE] (
  [ZI_ZIPCODE]varchar(7) COLLATE Korean_Wansung_CI_AS NOT NULL,
  [ZI_SIDO]varchar(8) COLLATE Korean_Wansung_CI_AS NULL,
  [ZI_GUGUN]varchar(30) COLLATE Korean_Wansung_CI_AS NULL,
  [ZI_DONG]varchar(60) COLLATE Korean_Wansung_CI_AS NULL,
  [ZI_BUNJI]varchar(20) COLLATE Korean_Wansung_CI_AS NULL,
  PRIMARY KEY CLUSTERED ([ZI_ZIPCODE])
);