select
datediff(dd,'1999-02-15','2000-02-15') as 'day',
AA.EM_CODE,
AA.CO_COMPANYCODE,
AA.COMPANY_NAME,
AA.CO_DEPARTCODE,
AA.DEPART_NAME,
AA.PO_NAME,
AA.EM_NAME,
Count(AA.EM_CODE) as ATCNT,
SUM(AA.JIKAK) as JIKAKCNT,
SUM(AA.JOTAE) as JOTAECNT
From
(select
a.AT_DATE,
b.EM_CODE,
b.CO_COMPANYCODE,
b.COMPANY_NAME,
b.CO_DEPARTCODE,
b.DEPART_NAME,
b.PO_NAME,
b.EM_NAME,
CASE
WHEN a.AT_INRESULT = 'N' then 1
ELSE 0 END as JIKAK,
CASE
WHEN a.AT_OUTRESULT = 'N' then 1
ELSE 0 END as JOTAE
from TB_ATEVENT a
  Inner Join
  ( select a.CA_CARDNO,a.GROUP_CODE,a.CO_COMPANYCODE,a.EM_CODE,
  b.CO_DEPARTCODE,b.EM_NAME,c.CO_NAME as COMPANY_NAME,d.CO_NAME as DEPART_NAME,   b.PO_POSICODE,e.PO_NAME
  from TB_CARD a
  INNER JOIN TB_EMPLOYEE b
  ON (a.GROUP_CODE = b.GROUP_CODE
  AND a.EM_CODE = b.EM_CODE
  AND a.CO_COMPANYCODE = b.CO_COMPANYCODE)
  LEFT JOIN TB_COMPANY c
  ON (b.GROUP_CODE = c.GROUP_CODE
  AND b.CO_COMPANYCODE = c.CO_COMPANYCODE
  AND c.CO_GUBUN = '1')
  LEFT JOIN TB_COMPANY d
  ON (b.GROUP_CODE = d.GROUP_CODE
  AND b.CO_COMPANYCODE = d.CO_COMPANYCODE
  AND b.CO_DEPARTCODE = d.CO_DEPARTCODE
  AND d.CO_GUBUN = '2')
  LEFT JOIN TB_POSI e
  ON (b.GROUP_CODE = e.GROUP_CODE
  AND b.PO_POSICODE = e.PO_POSICODE) ) b
  ON ( a.GROUP_CODE = b.GROUP_CODE
  AND a.CA_CARDNO = b.CA_CARDNO ) ) AA
GROUP BY
AA.EM_CODE,
AA.CO_COMPANYCODE,
AA.COMPANY_NAME,
AA.CO_DEPARTCODE,
AA.DEPART_NAME,
AA.PO_NAME,
AA.EM_NAME
Order by AA.CO_COMPANYCODE,AA.EM_CODE

