select *
from TB_DEVICECARDNO b
Inner Join TB_DOOR a
 ON ( a.GROUP_CODE = b.GROUP_CODE 
 AND a.AC_NODENO = b.AC_NODENO 
 AND a.AC_MCUID = b.AC_MCUID 
 AND a.AC_ECUID = b.AC_ECUID ) 
Inner JOIN
(select a.GROUP_CODE,
        a.CA_CARDNO,
        b.EM_NAME,
        b.CO_COMPANYCODE,
        c.CO_NAME as CO_COMPANYNAME,
        b.CO_DEPARTCODE,
        d.CO_NAME as CO_DEPARTNAME,
        b.PO_POSICODE,
        e.PO_NAME
from TB_CARD a 
Inner Join TB_EMPLOYEE b
ON ( a.GROUP_CODE = b.GROUP_CODE
AND a.CO_COMPANYCODE = b.CO_COMPANYCODE
AND a.EM_CODE = b.EM_CODE)
Left Join TB_COMPANY c
On (b.GROUP_CODE = c.GROUP_CODE
AND b.CO_COMPANYCODE = c.CO_COMPANYCODE
AND c.CO_GUBUN = '1')
Left Join TB_COMPANY d
ON (b.GROUP_CODE = d.GROUP_CODE
AND b.CO_COMPANYCODE = d.CO_COMPANYCODE
AND c.CO_DEPARTCODE = d.CO_DEPARTCODE
AND c.CO_GUBUN = '2')
Left Join TB_POSI e
ON (b.GROUP_CODE = e.GROUP_CODE
AND b.PO_POSICODE = e.PO_POSICODE )
) c
ON ( b.GROUP_CODE = c.GROUP_CODE
AND b.CA_CARDNO = c.CA_CARDNO )

