select f.MO_MONTH,
CASE
WHEN f.MO_01  = '0' THEN ''
WHEN f.MO_01  = '1' THEN '¡Û'
WHEN f.MO_01  = '2' THEN '¡ä'
WHEN f.MO_01  = '3' THEN '¡â'
WHEN f.MO_01  = '4' THEN '¡ß'
WHEN f.MO_01  = 'A' THEN 'X'
WHEN f.MO_01  = 'B' THEN '¨Ô'
WHEN f.MO_01  = 'C' THEN '¡Ù'
WHEN f.MO_01  = 'D' THEN '¡Ú'
ELSE '' END as MO_01,
  b.CO_COMPANYCODE,b.CO_DEPARTCODE,b.EM_CODE,b.EM_NAME,  c.CO_NAME as COMPANY_NAME,d.CO_NAME as DEPART_NAME,e.PO_NAME from TB_MONTHAT f   Inner Join TB_CARD a   ON (f.GROUP_CODE = a.GROUP_CODE   AND f.CA_CARDNO = a.CA_CARDNO)    INNER JOIN TB_EMPLOYEE b      ON (a.GROUP_CODE = b.GROUP_CODE     AND a.EM_CODE = b.EM_CODE     AND a.CO_COMPANYCODE = b.CO_COMPANYCODE)    LEFT JOIN TB_COMPANY c     ON (b.GROUP_CODE = c.GROUP_CODE    AND b.CO_COMPANYCODE = c.CO_COMPANYCODE    AND c.CO_GUBUN = '1')    LEFT JOIN TB_COMPANY d     ON (b.GROUP_CODE = d.GROUP_CODE     AND b.CO_COMPANYCODE = d.CO_COMPANYCODE     AND b.CO_DEPARTCODE = d.CO_DEPARTCODE     AND d.CO_GUBUN = '2')    LEFT JOIN TB_POSI e     ON (b.GROUP_CODE = e.GROUP_CODE    AND b.PO_POSICODE = e.PO_POSICODE)  Where f.GROUP_CODE = '1234567890'  AND f.MO_MONTH = '200710'  AND (  ( b.CO_COMPANYCODE = '001'  AND b.CO_DEPARTCODE = '001')  )
