select a.CA_CARDNO,a.GROUP_CODE,a.CO_COMPANYCODE,a.EM_CODE,
  b.CO_DEPARTCODE,b.EM_NAME,c.CO_NAME as COMPANY_NAME,d.CO_NAME as DEPART_NAME,   b.PO_POSICODE,e.PO_NAME
from
(select a.CA_CARDNO,a.GROUP_CODE,a.EM_CODE,a.CO_COMPANYCODE
from TB_CARD a
Where Not Exists
(select * from TB_ATEVENT b
where b.AT_DATE = '20071001'
AND a.GROUP_CODE = b.GROUP_CODE
AND a.CA_CARDNO = b.CA_CARDNO) ) a
  INNER JOIN TB_EMPLOYEE b
  ON (a.GROUP_CODE = b.GROUP_CODE
  AND a.EM_CODE = b.EM_CODE
  AND a.CO_COMPANYCODE = b.CO_COMPANYCODE)
  LEFT JOIN TB_COMPANY c
  ON (b.GROUP_CODE = c.GROUP_CODE
  AND b.CO_COMPANYCODE = c.CO_COMPANYCODE
  AND c.CO_GUBUN = '1')
  LEFT JOIN TB_COMPANY d
  ON (b.GROUP_CODE = d.GROUP_CODE
  AND b.CO_COMPANYCODE = d.CO_COMPANYCODE
  AND b.CO_DEPARTCODE = d.CO_DEPARTCODE
  AND d.CO_GUBUN = '2')
  LEFT JOIN TB_POSI e
  ON (b.GROUP_CODE = e.GROUP_CODE
  AND b.PO_POSICODE = e.PO_POSICODE)
Order by a.CO_COMPANYCODE,b.CO_DEPARTCODE,a.EM_CODE
